######################################################################
# Automatically generated by qmake (3.1) Sat Apr 14 19:20:41 2018
######################################################################

TEMPLATE = vcapp
CONFIG +=  qt debug_and_release windows console
TARGET = "Commande FPGA"
INCLUDEPATH += .
HEADERS += CommunicationFPGA.h Input_FPGA.h Registres.h
SOURCES += Input_FPGA.cpp 
LIBS += CommunicationFPGA.lib
QT += widgets
